### ISSUE TITLE
Build environment prerequisites

### ISSUE THREAD

**Issue by BarclayII** [davidgao/AnotherMetro#1]
@davidgao 
Can you write a brief list of prerequisites including coding environment, building environment, etc.?
Thanks

**Comment by davidgao** [comment]
Accepted.
1. A running JDK version 1.7 or 1.8. Both oracle and openJDK are usable. openJDK  will run a little bit slower but has no difference on behavior. GCJ totally useless. JDK version 1.6 cannot compile for Android 5.x/6.0. Android studio refuse to run on JDK 1.9.
2. Set JAVA_HOME variable properly.
3. Download Android studio **DIRECTLY FROM GOOGLE**. Extract it and follow its instructions.
